FROM python:3.9

# Install cron
RUN apt-get update && apt-get install -y cron

# Copy the script into the container
COPY 2.py /app/2.py

# Set up cron job
COPY cronjob_2 /etc/cron.d/cronjob_2

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cronjob_2

# Apply cron job
RUN crontab /etc/cron.d/cronjob_2

# Start cron in the foreground
CMD ["cron", "-f"]