FROM python:3.9

# Install cron
RUN apt-get update && apt-get install -y cron

# Copy the script into the container
COPY the_ftp_import.py /app/the_ftp_import.py

# Set up cron job
COPY cronjob_the_ftp_import /etc/cron.d/cronjob_the_ftp_import

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cronjob_the_ftp_import

# Apply cron job
RUN crontab /etc/cron.d/cronjob_the_ftp_import

# Start cron in the foreground
CMD ["cron", "-f"]